export const EP = {
  AUTH: 'auth',
  EMPLOYEE: 'employee',
  CLIENT: 'client',
  TASK: 'task',
  TICKET: 'ticket',
  TIMESHEET: 'timesheet',
  MASTER: 'master',
  SERVICES: 'services',
  PERMISSIONS: 'permissions',
  ATTENDANCE: 'attendance',
  DASHBOARD: 'dashboard',
  CALENDAR: 'calendar',
  MENU: 'menu',
  CHARTS: 'charts',
  DOCUMENT: 'document',
  DOCUMENTTYPE: 'documenttype',
  YEAR: 'year',
  CLIENT_TYPE: 'clienttype',
} as const;
